apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.cronjob.name }}
spec:
  schedule: "{{ .Values.cronjob.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: {{ .Values.cronjob.name }}
              image: {{ .Values.cronjob.image }}:{{ .Values.cronjob.imageTag }}
              args:
                - /bin/sh
                - -c
                - echo "This is test dependency cron Job!"
          restartPolicy: OnFailure